### PR TITLE
Fix typo in test.yml

### PR DESCRIPTION
**Pull request by gaby**
- Fix missing comma from #285 

@tfeldmann

### CODE REVIEW

**Comment by gaby** [comment]
That explains why the CI didnt run in #285 which github was more clear about that. GitLab would fail the whole PR if the ci file has typos 😂

**Comment by gaby** [comment]
@tfeldmann Py3.6 is EOL, can I remove it from the test matrix?

**Comment by tfeldmann** [comment]
Yes, that should be ok. Could you create a separate PR for that and update the dependencies for python >= 3.7 as well?

**Comment by gaby** [comment]
> Yes, that should be ok. Could you create a separate PR for that and update the dependencies for python >= 3.7 as well?

Will do!

**Pull request merged**
