### PR TITLE
F33 file size filter

### PR DESCRIPTION
**Pull request by mope1**

### CODE REVIEW

**Comment by mope1** [comment]
should be ok to merge this when you have time to review :)

**Comment by tfeldmann** [comment]
Thank you very much for this, great work! I'll test this a bit and then merge 👍

**Comment by mope1** [comment]
It looks like it is broken on Windows, working on a fix

**Comment by tfeldmann** [comment]
Hey. I'm sorry this took so long. I wasn't satisfied with the filter syntax so I had to add some changes. Furthermore I added integration tests.

**Pull request merged**
