### PR TITLE
F25 rule targets folders

### PR DESCRIPTION
**Pull request by mope1**
https://github.com/tfeldmann/organize/issues/25

### CODE REVIEW

**Comment by mope1** [comment]
this is already pretty solid but will cause the need for changes in file size filter https://github.com/tfeldmann/organize/pull/34

i'll wait until the file size PR is merged, then merge it into this branch from upstream with any other changes, and then change it up so that it recursively adds all the files when the path given to the file size filter is a folder

another TODO is good documentation for this feature, because otherwise it will just confuse people and suck.

**Comment by simonsan** [comment]
#34 is merged, just asking because I'm looking forward to operate on folders (for example get rid of empty ones or just move them completely) with organize. Any updates about this PR? Cheers!

**Comment by mope1** [comment]
For future reference, this PR is a **horrible pre-alpha demo** of the theoretical concept of a flag that would bend `organize` to somehow target folders without causing horrible bugs and deleting all your files possibly. 

_( Personally, when I was thinking about folder operations, I opened a mental pandoras box when I started thinking about having some sort of rollback feature in case any operation in the config file fails, which is currently super-not-supported by organize or its architecture )_ 

 Possibly, it would be easiest to just build a a new tool with some learnings in mind:
- Folder operations in mind from the start, especially in the yaml file format, and plan for a GUI that generates the yaml
- A clever file-system specific testing framework
- Treat config files as operation sets
- Possibily file system integration, which would probably nail it down to a specific platform or force implementation of fallbacks. Alternatively, just use some tricks to reduce data loss in case of failure/disk full/etc scenarios
- Roll back all operations on operation set failure and have concise logs instead of spamming every single occurence sequentially

I'm closing this as it's outdated, let's see where `organize` goes from here.

**Comment by tfeldmann** [comment]
Thank you for the summary. Folder operations are in the works. I'm thinking about undo functionality, too. I want to keep it simple so maybe just emit a `reverse` method if possible and write a new `undo.yaml` which rolls back everything possible.

**Comment by simonsan** [comment]
What would be the difference working on top of folders? How are you imagining it?

Would you like to "tidy" up the contents of a folder (over the complete folder hierarchy downwards) as well or threat the folder itself as a "file" and sort it away as is?

I think these are two different use cases then, will they be both possible then?

**Comment by tfeldmann** [comment]
> Would you like to "tidy" up the contents of a folder (over the complete folder hierarchy downwards) as well or threat the folder itself as a "file" and sort it away as is?

Tidying the contents of a folder is exactly what you can do with organize right now. Additionally one should be able to create rules which target only folders and move / copy / delete them depending on folder name, files contained, folder size etc.

**Pull request closed without merging**
